
HW2: lltable llparser
llparser: llparser.cpp llparser.h main.cpp
	g++ -g -std=c++0x -I ../Lexer -L ../Lexer -o llparser main.cpp llparser.cpp -lSLexer
lltable: lltable.cpp
	g++ -g -std=c++0x -o lltable lltable.cpp

